trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Install Node.js
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Install project dependencies
      cd ./path/to/your/react/app
      npm install
    displayName: 'Install dependencies'

  - script: |
      # Build the React application
      cd ./path/to/your/react/app
      npm run build
    displayName: 'Build React app'