apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This should match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

